name = "pixelkritzel"
license = "MIT"
licenselink = "https://github.com/vimux/blank/blob/master/LICENSE.md"
description = "Modified blank starter Hugo theme for developers."
homepage = "https://github.com/vimux/blank/"
tags = ["blog", "plain", "blank", "starter"]
features = ["blog"]
min_version = 0.19

[author]
  name = "Vimux"
  homepage = "https://github.com/vimux"
